import { createFileRoute, Link } from "@tanstack/react-router";
import dogWeddingAsset from "@/assets/dog-wedding-real.png";
import dogWeddingSocial1Asset from "@/assets/dog-wedding-social-1.jpg";
import dogWeddingSocial2Asset from "@/assets/dog-wedding-social-2.jpg";
import { DogDoodle, PageShell } from "@/components/portfolio-shell";

export const Route = createFileRoute("/work/dog-wedding")({
  head: () => ({ meta: [{ title: "The Dog Wedding Poster — Ananya Singh" }, { name: "description", content: "The Dog Wedding playful poster design case study by Ananya Singh." }, { property: "og:title", content: "The Dog Wedding Poster — Ananya Singh" }, { property: "og:description", content: "A joyful illustrated poster for a very important four-legged celebration." }, { property: "og:type", content: "article" }, { property: "og:url", content: "/work/dog-wedding" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/work/dog-wedding" }] }),
  component: DogWeddingCaseStudy,
});

function DogWeddingCaseStudy() {
  return <PageShell><article className="bg-peach/35">
    <header className="relative mx-auto max-w-screen-2xl px-5 pb-16 pt-16 md:px-10 md:pb-24 md:pt-24"><Link to="/" hash="work" className="text-xs uppercase text-muted-foreground">← Back to work</Link><DogDoodle className="doodle-drift absolute right-10 top-20 hidden w-28 stroke-wine stroke-[1.5] text-wine md:block"/><p className="mt-20 text-xs uppercase text-wine">02 · Poster Design · 2025</p><h1 className="mt-4 max-w-6xl font-display text-[19vw] leading-[0.72] md:text-[13vw]">The Dog<br /><em>Wedding</em></h1><div className="mt-14 grid gap-8 border-t border-wine/30 pt-6 md:grid-cols-2"><p className="font-display text-2xl md:text-3xl">A celebration where every guest gets a treat.</p><p className="max-w-lg text-sm leading-relaxed text-muted-foreground md:justify-self-end">A playful wedding poster created for a very important four-legged celebration—full of charm, ceremony and just enough mischief.</p></div></header>
    <section className="grid bg-wine px-5 py-16 md:grid-cols-12 md:px-10 md:py-24"><div className="md:col-span-7 md:col-start-2"><img src={dogWeddingAsset} width={748} height={977} alt="The Dog Wedding poster featuring two dogs in wedding attire" className="w-full" /></div><aside className="mt-10 text-primary-foreground md:col-span-2 md:col-start-10 md:mt-24"><p className="text-xs uppercase text-primary-foreground/60">Visual language</p><p className="mt-4 font-display text-3xl">Part invitation,<br />part keepsake,<br /><em>all joy.</em></p><div className="mt-10 space-y-2 text-xs uppercase text-primary-foreground/65"><p>Hand-drawn illustration</p><p>Expressive display type</p><p>Vintage print texture</p><p>Floral &amp; paw motifs</p></div></aside></section>
    <section className="mx-auto grid max-w-screen-xl gap-14 px-5 py-20 md:grid-cols-12 md:px-10 md:py-32"><div className="md:col-span-4"><p className="text-xs uppercase text-muted-foreground">Design objective</p><h2 className="mt-4 font-display text-5xl">Formal,<br /><em>but furry.</em></h2></div><div className="md:col-span-6 md:col-start-7"><p className="text-lg leading-relaxed">The piece balances the familiar visual language of a traditional wedding invitation with the warmth and humour of its canine subjects.</p><p className="mt-6 text-sm leading-relaxed text-muted-foreground">Burgundy grounds the composition, while dusty florals, imperfect linework and small hidden details reward a closer look. The oversized title gives the poster ceremony; the dogs make sure it never feels too serious.</p><div className="mt-12 border-y border-wine/30 py-6"><p className="font-display text-3xl italic text-wine">good dogs · brighter days · same paws forever</p></div></div></section>
    <section className="border-t border-wine/30 px-5 py-20 md:px-10 md:py-24"><div className="mx-auto max-w-screen-2xl"><p className="text-xs uppercase text-muted-foreground">Social media cuts</p><h2 className="mt-4 font-display text-5xl md:text-7xl">The invite,<br /><em>on the feed.</em></h2><div className="mt-12 grid gap-8 sm:grid-cols-2"><figure className="bg-paper"><img src={dogWeddingSocial1Asset} width={1080} height={1080} loading="lazy" alt="Barksy Mumbai's 1st Dog Wedding social post — two golden retrievers in wedding attire" className="aspect-square w-full object-cover" /><figcaption className="mt-2 text-[10px] uppercase text-muted-foreground">01 · Mumbai's cutest event just dropped</figcaption></figure><figure className="bg-paper"><img src={dogWeddingSocial2Asset} width={1170} height={1170} loading="lazy" alt="Barksy dog wedding social post — vintage car with dogs driving to the wedding" className="aspect-square w-full object-cover" /><figcaption className="mt-2 text-[10px] uppercase text-muted-foreground">02 · The paw-fect wedding of the year is calling</figcaption></figure></div></div></section>
    <section className="mx-auto max-w-screen-xl px-5 py-20 md:px-10 md:py-20"><Link to="/work/crockey" className="flex items-end justify-between border-t border-wine/30 pt-6"><span className="text-xs uppercase text-muted-foreground">Next project</span><span className="font-display text-4xl md:text-6xl">Crockey →</span></Link></section>
  </article></PageShell>;
}
