import { createFileRoute, Link } from "@tanstack/react-router";
import crockeyProjectAsset from "@/assets/crockey-real-project.png.asset.json";
import spreadOneAsset from "@/assets/crockey-spread-1.png.asset.json";
import spreadTwoAsset from "@/assets/crockey-spread-2.png.asset.json";
import { PageShell } from "@/components/portfolio-shell";

export const Route = createFileRoute("/work/crockey")({
  head: () => ({ meta: [{ title: "Crockey Catalogue — Ananya Singh" }, { name: "description", content: "Crockey catalogue design case study by graphic designer Ananya Singh." }, { property: "og:title", content: "Crockey Catalogue — Ananya Singh" }, { property: "og:description", content: "An editorial catalogue bringing product imagery and information into a calm, tactile system." }, { property: "og:type", content: "article" }, { property: "og:url", content: "/work/crockey" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/work/crockey" }] }),
  component: CrockeyCaseStudy,
});

function CrockeyCaseStudy() {
  return <PageShell>
    <article>
      <header className="mx-auto max-w-screen-2xl px-5 pb-16 pt-16 md:px-10 md:pb-24 md:pt-24"><Link to="/" hash="work" className="text-xs uppercase text-muted-foreground">← Back to work</Link><p className="mt-20 text-xs uppercase text-wine">01 · Catalogue Design · 2025</p><h1 className="mt-4 font-display text-[22vw] leading-[0.7] md:text-[16vw]">Crockey</h1><div className="mt-14 grid gap-8 border-t border-border pt-6 md:grid-cols-12"><p className="font-display text-2xl md:col-span-5 md:text-3xl">A quiet, considered catalogue for objects made to live with.</p><dl className="grid grid-cols-2 gap-5 text-xs uppercase text-muted-foreground md:col-span-5 md:col-start-8"><div><dt className="text-foreground">Discipline</dt><dd className="mt-2">Editorial Design</dd></div><div><dt className="text-foreground">Role</dt><dd className="mt-2">Art Direction · Layout</dd></div><div><dt className="text-foreground">Typography</dt><dd className="mt-2">Editorial Serif · Grotesk</dd></div><div><dt className="text-foreground">Palette</dt><dd className="mt-2">Ivory · Clay · Olive</dd></div></dl></div></header>
      <img src={crockeyProjectAsset.url} width={768} height={963} alt="Crockey curated ceramic collection with blossom branches" className="mx-auto max-h-[90svh] w-full bg-paper object-contain" />
      <section className="mx-auto grid max-w-screen-xl gap-12 px-5 py-20 md:grid-cols-2 md:px-10 md:py-32"><div><p className="text-xs uppercase text-muted-foreground">The objective</p><h2 className="mt-4 font-display text-5xl">Let each object<br /><em>breathe.</em></h2></div><div className="space-y-6 text-base leading-relaxed text-muted-foreground"><p>The catalogue needed to hold product details, pricing and atmosphere without feeling dense. The objective was to create a system where practical information felt as considered as the photography.</p><p>A restrained grid, generous margins and large typographic moments build pace across each spread. Warm neutrals support the objects rather than competing with them.</p></div></section>
      <figure className="group bg-foreground px-5 py-12 md:px-10 md:py-20"><img src={crockeyProjectAsset.url} width={768} height={963} loading="lazy" alt="Crockey curated ceramic collection artwork" className="mx-auto max-h-[90svh] w-full max-w-screen-2xl object-contain transition duration-700 group-hover:scale-[1.02]" /><figcaption className="mx-auto mt-4 max-w-screen-2xl text-xs uppercase text-background/60">Crockey · Curated ceramic collection</figcaption></figure>
      <section className="mx-auto max-w-screen-xl px-5 py-20 md:px-10 md:py-32"><div className="grid gap-12 md:grid-cols-3"><div><p className="text-xs uppercase text-muted-foreground">Typography</p><p className="mt-5 font-display text-5xl">Form meets<br />function.</p></div><div><p className="text-xs uppercase text-muted-foreground">Colour system</p><div className="mt-5 grid grid-cols-3 gap-2"><div className="aspect-square bg-wine"/><div className="aspect-square bg-peach"/><div className="aspect-square bg-olive"/></div></div><div><p className="text-xs uppercase text-muted-foreground">Final outcome</p><p className="mt-5 text-sm leading-relaxed text-muted-foreground">A flexible catalogue system that makes a broad collection feel unified, tactile and easy to navigate—while leaving room for the character of every object.</p></div></div><Link to="/work/dog-wedding" className="mt-28 flex items-end justify-between border-t border-border pt-6"><span className="text-xs uppercase text-muted-foreground">Next project</span><span className="font-display text-4xl md:text-6xl">The Dog Wedding →</span></Link></section>
    </article>
  </PageShell>;
}